### ISSUE TITLE
Functions about grpc

### ISSUE THREAD

**Issue by lwmonster** [grpc/grpc-experiments#143]
hi :

I've gone through the cpp tutorial, and I didn't find any other further docs. So what I want to know are:
1、 Is grpc easy to deploy a distributed server cluster? 
2、 If 1 is yes then does the cluster support Load Balancing ?
3、 Dose it support  HA by doing a config? 

BTW:
     Is there a maillist or mail group about grpc?  I didn't find.

Thank you very much~

**Comment by nicolasnoble** [comment]
If you want more live discussions, you can find pointers to our IRC channel and mailing lists here: http://www.grpc.io/contribute/

**Comment by lwmonster** [comment]
OK， Thank You, found it.

I haven't read the source code, and I didn't found the detailed docs,  so can you tell me about the questions above?    
Mostly about the Load Balancing and HA ~~  

Very grateful for your reply!!!

**Comment by louiscryan** [comment]
Just for posterity as we discussed this on the IRC channel.

1 - Yes, you can use HAProxy to do load-balancing. Will provide a recipe for that soon and client-side load balancing is on the roadmap. Other LBs should work, need to do testing.
2. See above.
3. Aside from LB what other HA features do you have in mind? Healthchecking is also on the roadmap.
