### ISSUE TITLE
cannot compile helloworld example

### ISSUE THREAD

**Issue by carlosvin** [grpc/grpc-experiments#145]
/usr/bin/ld: warning: libgpr.so.0, needed by /usr/local/lib/libgrpc.so, not found (try using -rpath or -rpath-link)
After previous line errors with missing references for gpr_split_host_port, gpr_timespec_to_micros, etc. 

I'm just following this tutorial https://github.com/grpc/grpc-common/tree/master/cpp

**Comment by nicolasnoble** [comment]
This would indicate you didn't install grpc. Did you ?

**Comment by carlosvin** [comment]
Yes, I did. 
 $ git clone https://github.com/grpc/grpc.git
 $ cd grpc
 $ git submodule update --init
 $ make 
 $ sudo make install

**Comment by nicolasnoble** [comment]
Hm, interesting. Could you provide the output of ldd /usr/local/lib/libgrpc.so.0 ? Also verify that libgpr.so is properly present in /usr/local/lib - It seems that for some reasons, your system can't find the dependencies properly, which is very odd if it can find libgrpc.so but not libgpr.

Could you also try running sudo ldconfig ? This should refresh your library cache. This is run by the Makefile already, but just to make sure.

**Comment by carlosvin** [comment]
I don't have the output now, in as soon as I get my laptop I'll send it. 

Meanwhile, maybe the problem is in Makefile: https://github.com/grpc/grpc-common/blob/master/cpp/helloworld/Makefile

LDFLAGS = -L/usr/local/lib -lgrpc -lgrpc++ -lprotobuf -lpthread -ldl

lgpr is not there. By the way, what this library is for?

**Comment by nicolasnoble** [comment]
Adding -lgpr here shouldn't hurt (and it fact would be needed in case someone installed the static libraries - plus it's probably a general good practice in that case), but I'd be surprised if it'd help. Basically, libgrpc.so depends on libgpr.so, so loading libgrpc.so should trigger a cascade loading of libgpr.so. Your error message says that libgrpc.so couldn't find libgpr.so when being loaded. So the dependency link is properly there, and adding one shouldn't change anything. But please try and let me know :-)

Here's an example of what I'm talking about:

```
pixel@grumpy:/usr/lib$ ldd libbind9.so.90
        linux-vdso.so.1 =>  (0x00007fffb93e7000)
        libdns.so.100 => /usr/lib/libdns.so.100 (0x00007f7583967000)
        libisccfg.so.90 => /usr/lib/libisccfg.so.90 (0x00007f7583744000)
        libisc.so.95 => /usr/lib/libisc.so.95 (0x00007f75834e1000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f758311c000)
        libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f7582ed6000)
        libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f7582c0a000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7582a06000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f75827e8000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f758240d000)
        libGeoIP.so.1 => /usr/lib/x86_64-linux-gnu/libGeoIP.so.1 (0x00007f75821de000)
        libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f7581e78000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7583f5b000)
        libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f7581c48000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f7581a44000)
        libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f7581839000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f7581634000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f7581419000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f7581200000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f7580fdd000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7580cd7000)
```

The libbind9.so library depends on all these, and if you create a software that uses libbind9, you shouldn't have to explicitly link with all of them.


GPR stands for Google Public Runtime. It has been a silent release embedded inside grpc. Its point is to provide a limited set of cross platform features and helpers to allocate memory, spawn threads, handle mutexes, etc.

**Comment by FrankSnail** [comment]
I  also encountered problem,there were several messages like '/usr/bin/ld: cannot find -lgrpc++_unsecure',but I found the corresponding file libxx.so in the $GRPC_ROOT/libs/opt directory for each lost -libxx.then I created a soft link for each .so file in /usr/lib by  command 'sudo ln -s  $GRPC_ROOT/libs/opt/libxx.so /usr/lib/libxx.so ', the problem was then solved. 
there is a better way to solve it is append the  $GRPC_ROOT/libs/opt to the end of /etc/ld.so.conf but it doesn't work and i don't know why.

**Comment by louiscryan** [comment]
@nicolasnoble is this resolved/obsolete now?

**Comment by rcordeau** [comment]
So I am seeing the same issue if I checkout release-0_13_0 - it doesn't build libgpr.so.  The tip of master will build libgpr.so (version 14-dev) just fine.  How did it go missing?
