### ISSUE TITLE
Protoc for Android documentation

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-experiments#156]
There doesn't seem to be any documentation anywhere on how to run protoc for Android. The javatutorial doesn't use nano proto, so the protoc command documented there doesn't work. We need to add some documentation that provides a command similar to the comment in https://github.com/grpc/grpc-java/commit/dcff315dc3ae17f3eefbdaa262add0f7dbe551ec

**Comment by LisaFC** [comment]
I'm working on a proto3 update to the proto docs at the moment - haven't got into language specific docs but the general language guide will have instructions on how to run protoc for each supported language, inc Nano. Hoping to get it finished soon. Will be in the devsite protobuf site rather than here, as it's not just gRPC-applicable.

**Comment by ejona86** [comment]
That sounds great. After that is done we can reference it, but then still include an example command line, because it does require multiple flags that are non-obvious (passing nano=true to grpc, and ignore-services=true to nano)

**Comment by zsurocking** [comment]
We have an nano protoc commandline example at the bottom of the page: https://github.com/grpc/grpc-java/tree/master/compiler

I can also mention that in Android helloworld example

**Comment by ejona86** [comment]
@zsurocking, ah, right. Given that someone looking at the Android example would have trouble finding that, it probably makes sense to also add it to the example.

**Comment by boosh** [comment]
@zsurocking The nano protoc command at the bottom of the page you linked to only generates the *Grpc class, but not the *Request classes when I run it against my project. 

I.e. my version of the file https://github.com/grpc/grpc-common/blob/master/java/android/app/src/main/java/io/grpc/helloworldexample/GreeterGrpc.java IS generated, but my version of the file  https://github.com/grpc/grpc-common/blob/master/java/android/app/src/main/java/io/grpc/helloworldexample/Helloworld.java is NOT generated (and I've no idea how to generate it).

I'm running:

```
protoc --plugin=protoc-gen-java_rpc=../../grpc-java/compiler/build/binaries/java_pluginExecutable/java_plugin \
  --java_rpc_out=nano=true:../client/src/main/generated-sources \
  --proto_path=src/main/proto/ src/main/proto/api.proto
```

**Comment by pokerG** [comment]
@boosh  you can use(Change to the `grpc-java` directory)

<pre><code>protoc --plugin=protoc-gen-java_rpc=compiler/build/binaries/java_pluginExecutable/java_plugin--java_rpc_out=nano=true:"examples/build/generated-sources/main/" --proto_path="examples/src/main/proto/ --
javanano_out=ignore_services=true:examples/build/generated-sources/main/ examples/src/main/proto/helloworld.proto</code></pre>

add  <code>--javanano_out=ignore_services=true:DST_DIR</code>

**Comment by boosh** [comment]
@pokerG Perfect, thanks!

**Comment by MaxDZ8** [comment]
I see this is still opened.
I'm starting to look at grpc for an Android project with JavaNano protocol buffers.

I haven't looked at anything specific to grpc yet but as a start I'd like to see this issue updated and hopefully closed.
