### ISSUE TITLE
Non existent windows / Visual Studio documentation

### ISSUE THREAD

**Issue by bluebird75** [grpc/grpc-experiments#173]
Documentation for Windows / Visual Studio is non-existent. There are vsprojects files, which is nice. The file do compile things, which is good. However, nowhere is there help on how to fix problems and what to expect. Please address the following hiccups :

# Comping gRPC #
* compiling fails on missing openssl includes
* solution : run build_openssl_x86.bat in a command-line with visual studio.
then compiling grpc works

# Generating protoc #
Now, I am trying to generate some C++ code. 
* Protoc would not compile because of some ruby problems in the ruby generator
   * solution 1 : deactivating ruby support fixed it.
   * solution 2 : point to the binary release

# Running protoc #
* According to helloworld tutorial, this works :

     protoc -I ../../protos/ --cpp_out=. --grpc_out=. --plugin=protoc-gen-grpc=grpc_cpp_plugin ../../protos/helloworld.proto

* This fails on the missing grpc_cpp_plugin plugin. 
    * Solution : I looked in many places, makefiles and so on but could not find how to create this plugin. Please help...

**Comment by saberwolf2015** [comment]
I have a same problem. Does anybody know how to build this plugin or how to build test example in grpc-common under Windows (visual studio 2013 c++)?

**Comment by jtattermusch** [comment]
The VS project have recently been refactored and I also added a short howto here: https://github.com/grpc/grpc/tree/master/vsprojects. You should no longer have trouble with openssl dependency.

**Comment by saberwolf2015** [comment]
I dont have a problem with openssl dependency, just i cant compile proto file to c++ class with grpc support because it need grpc_cpp_plugin, on linux that plugin successfully created and located in {path to grpc}/grpc/bins/opt/. But under windows we cant find it. Bui it neeeded to compile protobuf with grpc support: example from grpc-common:
protoc -I ../../protos/ --cpp_out=. --grpc_out=. --plugin=protoc-gen-grpc=grpc_cpp_plugin ../../protos/helloworld.proto

**Comment by nicolasnoble** [comment]
Did you notice the plugin was available in binary form on each release ?

https://github.com/grpc/grpc/releases/tag/release-0_6_0

**Comment by saberwolf2015** [comment]
Thank you, got it! Now i can compile protofile to c++ class with grpc, this way:
protoc -I c:\grpc\ --cpp_out=. --grpc_out=. --plugin=protoc-gen-grpc=c:\grpc\grpc_cpp_plugin.exe c:\grpc\helloworld.proto
And got helloworld.pb.h and helloworld.pb.cc

By the way, methods on page https://github.com/grpc/grpc-common/tree/master/cpp/helloworld
$ protoc -I ../../protos/ --grpc_out=. --plugin=protoc-gen-grpc=grpc_cpp_plugin ../../protos/helloworld.proto
$ protoc -I ../../protos/ --cpp_out=. ../../protos/helloworld.proto
for some reason dont work for me.
Command  protoc -I c:\grpc\ --grpc_out=. --plugin=protoc-gen-grpc=c:\grpc\grpc_cpp_plugin.exe c:\grpc\helloworld.proto
give errors:
helloworld.pb.h: Tried to insert into file that doesn't exist.
helloworld.pb.h: Tried to insert into file that doesn't exist.
helloworld.pb.cc: Tried to insert into file that doesn't exist.
helloworld.pb.cc: Tried to insert into file that doesn't exist.

and command:
protoc -I c:\grpc\  --cpp_out=. c:\grpc\helloworld.proto 
makes just plain protobuf files without grpc support.

Well, lets back to the main question. Now I want to compile c++ files to obj, i make:
cl -EHsc -c helloworld.pb.cc  -I c:\grpc\protobuf-master\src\ -I c:\grpc\grpc-master\include\
and got errors:
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.31101 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

helloworld.pb.cc
helloworld.pb.cc(688) : error C2512: 'helloworld::Greeter::Stub' : no appropriate default constructor available
helloworld.pb.cc(689) : error C2039: 'set_channel' : is not a member of 'helloworld::Greeter::Stub'
        c:\grpc\helloworld.pb.h(322) : see declaration of 'helloworld::Greeter::Stub'
helloworld.pb.cc(694) : error C2440: '<function-style-cast>' : cannot convert from 'const char *' to 'grpc::RpcMethod'
        No constructor could take the source type, or constructor overload resolution was ambiguous
helloworld.pb.cc(694) : error C2660: 'grpc::BlockingUnaryCall' : function does not take 4 arguments
helloworld.pb.cc(698) : error C2440: '<function-style-cast>' : cannot convert from 'const char *' to 'grpc::RpcMethod'
        No constructor could take the source type, or constructor overload resolution was ambiguous
helloworld.pb.cc(698) : error C2661: 'grpc::ClientAsyncResponseReader<helloworld::HelloReply>::ClientAsyncResponseReader
' : no overloaded function takes 5 arguments

Jn line 688 we have
std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub());
and in file c:\grpc\grpc-master\include\grpc++\impl\internal_stub.h class InternalStub actually not have default constructor, and this is really strange ...

Could you please explain to me what i doing wrong and give some advice how to successfully compile c++ example from grpc-common-master under windows?

**Comment by nicolasnoble** [comment]
Argh, okay :-D

So long story short here, you're using an outdated plugin while being on the "master" release of grpc. I should've thought of that when pointing you at the binary version of the plugin in the release. For a bit more details, see [this post on grpc.io](https://groups.google.com/forum/#!msg/grpc-io/c7NT5Y4jnCE/sstvQW9dwqsJ).

Which means you HAVE to compile your own plugin here... Exactly what I wanted to avoid. Sorry. Hopefully next release I won't break the plugin again :-)

Alright, let's try giving you some guidance so you can do it yourself. We should eventually have project files for that, but it's tied to protobuf, so we'll see how to handle that properly. This below is a quick and dirty solution. Hopefully you won't have to do that ever again.

1. Check out the grpc repository recursively - aka, make sure you have `third_party/protobuf` in there.

2. Go to `grpc\third_party\protobuf\vsprojects` and open `protobuf.sln` - ignore any warnings about gtest.

3. Switch the solution to "Release".

4. Open the `test_plugin` project and remove all of its headers and sources.

5. Add the following files to the `test_plugin` project: 
![add-existing](https://cloud.githubusercontent.com/assets/7281574/7330202/d9915e30-ea9e-11e4-958e-9a688492319a.png)

6. Modify the `test_plugin` project properties to add the paths `../../../` and `../../../include` to Configuration Properties -> C/C++ -> General -> Additional Include Directories:
![properties](https://cloud.githubusercontent.com/assets/7281574/7330252/b7b72dac-ea9f-11e4-8a79-95eef83b717a.png)

7. Build the `test_plugin` project.

  -->  the plugin will be available as `test_plugin.exe` in `grpc\third_party\protobuf\vsprojects\Release`. Rename it and move it to your convenience.

**Comment by saberwolf2015** [comment]
Thank you for fast and correct answer. I compiled plugin and got exe file.
Now new way of c++ code generation from protobuf declaration works as expected:

protoc -I c:\grpc\ --grpc_out=. --plugin=protoc-gen-grpc=c:\grpc\grpc_cpp_plugin.exe c:\grpc\helloworld.proto

protoc -I c:\grpc\ --cpp_out=. c:\grpc\helloworld.proto 

Now i also can make obj files (need compile with /MD or we get error "error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' " on link stage):

cl -EHsc -c helloworld.pb.cc -I c:\grpc\protobuf-master\src\ -I c:\grpc\grpc-master\include\ /MD
C:\grpc>cl -EHsc -c helloworld.grpc.pb.cc helloworld.pb.obj -I c:\grpc\protobuf-master\src\ -I c:\grpc\grpc-master\include\ /MD
cl -EHsc -c greeter_server.cc -I c:\grpc\protobuf-master\src\ -I c:\grpc\grpc-master\include\ /MD
cl -EHsc -c greeter_client.cc -I c:\grpc\protobuf-master\src\ -I c:\grpc\grpc-master\include\ /MD

Ok, all good we got obj files. Next link stage:
cl greeter_server.obj helloworld.pb.obj helloworld.grpc.pb.obj libprotobuf.lib grpc.lib gpr.lib grpc++.lib ws2_32.lib -link -LIBPATH:C:\grpc\lib

cl greeter_client.obj helloworld.pb.obj helloworld.grpc.pb.obj libprotobuf.lib grpc.lib gpr.lib grpc++.lib ws2_32.lib -link -LIBPATH:C:\grpc\lib

all good we got greeter_server.exe and greeter_client.exe
Launching server:
C:\grpc>greeter_server.exe
E0425 23:54:34.837000000  4620 ..\..\src\core\support\cpu_windows.c:42] Cannot determine number of CPUs: assuming 1
Server listening on 0.0.0.0:50051

Ignore that warning and launch client:
![greeter_client](https://cloud.githubusercontent.com/assets/12089390/7334265/00f13e00-eba8-11e4-9ff6-e005504e397c.png)


Well client side even got reply, but what on the server side?
![greeter_server_error](https://cloud.githubusercontent.com/assets/12089390/7334221/0170cbe4-eba7-11e4-99e8-489ca4d1af8f.png)
In first sight all works, but whats wrong with ReadFile Overlapping Error? Can it lead in a future troubles or i can just ignore it?

**Comment by jtattermusch** [comment]
The ReadFile Overlapped error probably indicates that the connection has been reset (because client has disconnected).  But the error message is strange indeed. 
Actually, our current progress with gRPC on windows is that calls from client succeed, but server has trouble handling its own shutdown and connections being closed by client (see bugs #546 and #1346).

Can you try to debug greeter_server and see why are you getting such strange error message?

**Comment by saberwolf2015** [comment]
Almost forgot to mention, to avoid error 
error C2664: 'void std::_Func_class<_Re
t,ServiceType *,grpc::ServerContext *,const RequestType *,ResponseType *>::_Set(std::_Func_base<_Ret,ServiceType *,grpc:
:ServerContext *,const RequestType *,ResponseType *> *)' : cannot convert argument 1 from '_Myimpl *' to 'std::_Func_bas
e<_Ret,ServiceType *,grpc::ServerContext *,const RequestType *,ResponseType *> *'

when building helloworld.grpc.pb.obj (
C:\grpc>cl -EHsc -c helloworld.grpc.pb.cc -I c:\grpc\protobuf-master\src\ -I c:\grpc\grpc-master\include\ /MD )

i'm changed line:
std::function< ::grpc::Status(Greeter::Service*, ::grpc::ServerContext*, const ::helloworld::HelloRequest*, ::helloworld::HelloReply*)>(&Greeter::Service::SayHello), this),
in helloworld.grpc.pb.cc
on 
std::mem_fn(&Greeter::Service::SayHello), this),

About error text, i'm looked into code (c:\grpc\grpc-master\src\core\iomgr\tcp_windows.c) found lines:
    char *utf8_message = gpr_format_message(info->wsa_error);
    gpr_log(GPR_ERROR, "ReadFile overlapped error: %s", utf8_message);
And got it - default code page on windows console is not utf8, so i make 
chcp 65001
then changed font on Lucida Console, and there is:
![image](https://cloud.githubusercontent.com/assets/12089390/7364872/b76a3486-eda4-11e4-9b03-4d6318d6a5fe.png)
My default OS language is russian, so this was common error "An existing connection was forcibly closed by the remote host".

**Comment by nicolasnoble** [comment]
Yep, that makes sense. There is clearly a refcounting issue if the OS is
closing the socket instead of our code.
