### ISSUE TITLE
Add to HTTP2-grpc spec client should RST_STREAM if it receives END_STREAM before half closing 

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-experiments#198]

**Comment by ejona86** [comment]
We may want to consider the implications of [HTTP/2 §8.1](https://httpwg.github.io/specs/rfc7540.html#rfc.section.8.1):

> An HTTP response is complete after the server sends - or the client receives - a frame with the END_STREAM flag set (including any CONTINUATION frames needed to complete a header block). A server can send a complete response prior to the client sending an entire request if the response does not depend on any portion of the request that has not been sent and received. When this is true, a server MAY request that the client abort transmission of a request without error by sending a RST_STREAM with an error code of NO_ERROR after sending a complete response (i.e., a frame with the END_STREAM flag). Clients MUST NOT discard responses as a result of receiving such a RST_STREAM, though clients can always discard responses at their discretion for other reasons.

I would totally believe we are doing that wrong today. It looks like it may be more appropriate to do it on the server-side since that is explicitly mentioned in the spec.

**Comment by ctiller** [comment]
Almost certain that C is doing this wrong also.

**Comment by ctiller** [comment]
Issued grpc/grpc#1661 to fix this for C core and associated wrapped languages.

**Comment by ejona86** [comment]
Java issues for client-side (grpc/grpc-java#2163) and server-side (grpc/grpc-java#2162)
