### ISSUE TITLE
The Node installation script/example does not work

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc-experiments#233]
The installation script installs the gRPC Node library globally. This is not very useful, because that does not satisfy package dependencies. So running `npm install` in `grpc-common/node` will still fetch the library from npm and fail because it does not have the proper `CXXFLAGS` and `LDFLAGS`.

**Comment by tbetbetbe** [comment]
As discussed
- this should update the installation script/instructions to do npm link
- we need to have a fix for

**Comment by astra-v** [comment]
I am having the same problem
..\ext\timeval.cc(36): fatal error C1083: Cannot open include file: 'grpc/grpc.
h': No such file or directory [D:\Work\Project\grpc-common\node\node_modules\gr
pc\build\grpc.vcxproj]

Please advice how to fix it

**Comment by cpettitt** [comment]
Hitting the same problem. Are there some manual steps we can use to work around this for now?

**Comment by cpettitt** [comment]
I was able to get the install to pass. The main trick seems to be using grpc@0.9.0 instead of grpc@0.9.1. Here's what I did:

```sh
brew install google-protobuf
brew install grpc
brew_root=`brew --prefix` CXXFLAGS=-I${brew_root}/include LDFLAGS=-L${brew_root}/lib npm install grpc@0.9.0
```

It seems grpc@09.1 has a compilation issue, at least on my system:

```
> grpc@0.9.1 install /Users/cpettitt/projects/fastina2/nodejs/node_modules/grpc
> node-gyp rebuild

  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
../ext/byte_buffer.cc:60:33: error: use of undeclared identifier 'grpc_raw_byte_buffer_create'; did you mean 'grpc_byte_buffer_create'?
  grpc_byte_buffer *byte_buffer(grpc_raw_byte_buffer_create(&slice, 1));
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                grpc_byte_buffer_create
/usr/local/include/grpc/grpc.h:163:19: note: 'grpc_byte_buffer_create' declared here
grpc_byte_buffer *grpc_byte_buffer_create(gpr_slice *slices, size_t nslices);
                  ^
../ext/byte_buffer.cc:74:3: error: use of undeclared identifier 'grpc_byte_buffer_reader_init'; did you mean 'grpc_byte_buffer_reader_next'?
  grpc_byte_buffer_reader_init(&reader, buffer);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  grpc_byte_buffer_reader_next
/usr/local/include/grpc/grpc.h:177:5: note: 'grpc_byte_buffer_reader_next' declared here
int grpc_byte_buffer_reader_next(grpc_byte_buffer_reader *reader,
    ^
../ext/byte_buffer.cc:74:41: error: cannot initialize a parameter of type 'gpr_slice *' with an lvalue of type 'grpc_byte_buffer *'
  grpc_byte_buffer_reader_init(&reader, buffer);
                                        ^~~~~~
/usr/local/include/grpc/grpc.h:178:45: note: passing argument to parameter 'slice' here
                                 gpr_slice *slice);
                                            ^
3 errors generated.
make: *** [Release/obj.target/grpc/ext/byte_buffer.o] Error 1
```

**Comment by eligeske** [comment]
This is the message received when following the "node getting started" on ubuntu using node 0.12.4

Any help would be appreciated! Thanks :)

npm ERR! Linux 3.16.0-40-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! grpc@0.9.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@0.9.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.
