### ISSUE TITLE
Supported languages in grpc 

### ISSUE THREAD

**Issue by amitkg29** [grpc/grpc-experiments#237]
Is C language on roadmap in list of supported languages for generated code in grpc? If yes, is there any timeline for it?

**Comment by ctiller** [comment]
It's something we've thought about, and would like to do - but not something we've had time for yet - and there's no timeline for it.

If anyone is interested in working on such a thing, I'd be happy to give pointers and feedback.

**Comment by amitkg29** [comment]
Thanks very much for the response. I am working on it and have initial implementation which is single threaded and based on libisc2. I will definitely like to discuss the design approach we have taken and refine it.
