### ISSUE TITLE
grpc noblocking server 

### ISSUE THREAD

**Issue by LuckyCloud** [grpc/grpc-experiments#252]
can grpc implement an c++ noblocking server？

**Comment by nicolasnoble** [comment]
Yes. See https://github.com/grpc/grpc-common/blob/master/cpp/helloworld/greeter_async_server.cc

**Comment by LuckyCloud** [comment]
I see it but it is also block on  poll 
#0  0x00007ffff633c0d3 in poll () from /lib64/libc.so.6
#1  0x00007ffff77c1098 in ?? () from /usr/local/lib/libgrpc.so.0
#2  0x00007ffff77c0c6e in grpc_pollset_work () from /usr/local/lib/libgrpc.so.0
#3  0x00007ffff77ca765 in grpc_completion_queue_next () from /usr/local/lib/libgrpc.so.0
#4  0x00007ffff7bc51bd in grpc::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) () from /usr/local/lib/libgrpc++_unsecure.so.0
#5  0x0000000000409d47 in grpc::CompletionQueue::Next(void**, bool*) ()
#6  0x000000000040a4f4 in ServerImpl::HandleRpcs() ()
#7  0x000000000040a0ae in ServerImpl::Run() ()
#8  0x0000000000409c6f in main ()

**Comment by nicolasnoble** [comment]
You can use AsyncNext to specify a deadline instead of just calling Next.

**Comment by LuckyCloud** [comment]
can you give me a example？

**Comment by nicolasnoble** [comment]
Something of that ilk, probably: https://gist.github.com/nicolasnoble/a40a81db45db4f025601

**Comment by louiscryan** [comment]
@nicolasnoble Is this resolved, is a doc update needed somewhere
